server:
  servlet:
    application-display-name: eureka-client
    context-path: /eureka/client/
  port: 8082
spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/