server:
  servlet:
    application-display-name: euraka-client
  port: 8082
spring:
  application:
    name: eureka-client

management:
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
    refresh:
      enabled: true
    
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/